# Window
WIDTH, HEIGHT = 1280, 720
WINDOW_CAPTION = "chessUCI"

# Board
PIECES_WIDTH, PIECES_HEIGHT = 90, 90
SQUARES_WIDTH, SQUARES_HEIGHT = 90, 90
BOARD_START_X, BOARD_START_Y = 50, HEIGHT - SQUARES_HEIGHT

FPS_CAP = 60
